
const housesData = [
    {
        id: 1,
        title: "3 bed room flat",
        baths: "2",
        beds: "3",
        size: "50/50",
        price: "85,000,000,000",
        location: "lagos",
        description: "Verified listings. Transparent prices. Move in faster.",
        image: "/images/3.jpeg",
        availability: true,
        like: false,
        showcase: true,
        isbanner: true,
        status: "sell",
        latitude: 6.1451,
        longitude: 6.7859,
    },
    {
        id: 2,
        title: "a room flat",
        baths: "1",
        beds: "1",
        size: "50/50",
        price: "3,000,000,000",
        location: "lagos",
        description: "Verified listings. Transparent prices. Move in faster.",
        image: "/images/2.jpeg",
        availability: true,
        like: false,
        showcase: true,
        isbanner: false,
        status: "rent",
        latitude: 8.1451,
        longitude: 5.7859,
    },
    {
        id: 3,
        title: "a room self-containner",
        baths: "1",
        beds: "1",
        size: "50/50",
        price: "500,000",
        location: "lagos",
        description: "Verified listings. Transparent prices. Move in faster.",
        image: "/images/11.jpg",
        availability: true,
        like: false,
        showcase: true,
        isbanner: true,
        status: "rent",
        latitude: 6.1451,
        longitude: 6.7859,
    },
    {
        id: 4,
        title: "2 room flat",
        baths: "2",
        beds: "2",
        size: "50/50",
        price: "3,000,000,000",
        location: "lagos",
        description: "Verified listings. Transparent prices. Move in faster.",
        image: "/images/5.jpeg",
        availability: true,
        like: false,
        showcase: false,
        isbanner: false,
        status: "rent",
        latitude: 8.1451,
        longitude: 8.7859,
    },
    {
        id: 5,
        title: "a room self-containner",
        baths: "1",
        beds: "1",
        size: "50/50",
        price: "500,000",
        location: "lagos",
        description: "Verified listings. Transparent prices. Move in faster.",
        image: "/images/6.jpg",
        availability: true,
        like: false,
        showcase: false,
        isbanner: false,
        status: "rent",
        latitude: 9.1451,
        longitude: 9.7859,
    },
    {
        id: 6,
        title: "a room self-containner",
        baths: "1",
        beds: "1",
        size: "50/50",
        price: "500,000",
        location: "lagos",
        description: "Verified listings. Transparent prices. Move in faster.",
        image: "/images/8.jpg",
        availability: true,
        like: false,
        showcase: false,
        isbanner: true,
        status: "rent",
        latitude: 7.1451,
        longitude: 7.7859,
    },
    {
        id: 7,
        title: "3 bed room flat",
        baths: "2",
        beds: "3",
        size: "50/50",
        price: "80,000,000,000",
        location: "lagos",
        description: "Verified listings. Transparent prices. Move in faster.",
        image: "/images/4.jpeg",
        availability: true,
        like: false,
        showcase: true,
        isbanner: true,
        status: "sell",
        latitude: 6.1451,
        longitude: 6.7859,
    },
    {
        id: 8,
        title: "3 bed room flat",
        baths: "2",
        beds: "3",
        size: "50/50",
        price: "66,000,000,000",
        location: "lagos",
        description: "Verified listings. Transparent prices. Move in faster.",
        image: "/images/5.jpeg",
        availability: true,
        like: false,
        showcase: true,
        isbanner: false,
        status: "sell",
        latitude: 6.2108,
        longitude: 7.0727,
    },
]

export default housesData;
